CREATE TABLE blocks (
    `chain_id` UInt256,
    `number` UInt256,
    `timestamp` UInt64 CODEC(Delta, ZSTD),
    `hash` FixedString(66),
    `parent_hash` FixedString(66),
    `sha3_uncles` FixedString(66),
    `nonce` FixedString(18),
    `mix_hash` FixedString(66),
    `miner` FixedString(42),
    `state_root` FixedString(66),
    `transactions_root` FixedString(66),
    `receipts_root` FixedString(66),
    `logs_bloom` String,
    `size` UInt64,
    `extra_data` String,
    `difficulty` UInt256,
    `total_difficulty` UInt256,
    `transaction_count` UInt64,
    `gas_limit` UInt256,
    `gas_used` UInt256,
    `withdrawals_root` Nullable(FixedString(66)),
    `base_fee_per_gas` Nullable(UInt64),
    `insert_timestamp` DateTime DEFAULT now(),
    `is_deleted` UInt8 DEFAULT 0,
    INDEX idx_timestamp timestamp TYPE minmax GRANULARITY 1,
    INDEX idx_hash hash TYPE bloom_filter GRANULARITY 1,
) ENGINE = ReplacingMergeTree(insert_timestamp, is_deleted)
ORDER BY (chain_id, number)
PARTITION BY chain_id
SETTINGS allow_experimental_replacing_merge_with_cleanup = 1;