// Code generated by mockery v2.50.4. DO NOT EDIT.

//go:build !production

package mocks

import (
	context "context"
	big "math/big"

	mock "github.com/stretchr/testify/mock"

	rpc "github.com/thirdweb-dev/indexer/internal/rpc"
)

// MockIRPCClient is an autogenerated mock type for the IRPCClient type
type MockIRPCClient struct {
	mock.Mock
}

type MockIRPCClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRPCClient) EXPECT() *MockIRPCClient_Expecter {
	return &MockIRPCClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockIRPCClient) Close() {
	_m.Called()
}

// MockIRPCClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIRPCClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIRPCClient_Expecter) Close() *MockIRPCClient_Close_Call {
	return &MockIRPCClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIRPCClient_Close_Call) Run(run func()) *MockIRPCClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRPCClient_Close_Call) Return() *MockIRPCClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIRPCClient_Close_Call) RunAndReturn(run func()) *MockIRPCClient_Close_Call {
	_c.Run(run)
	return _c
}

// GetBlocks provides a mock function with given fields: ctx, blockNumbers
func (_m *MockIRPCClient) GetBlocks(ctx context.Context, blockNumbers []*big.Int) []rpc.GetBlocksResult {
	ret := _m.Called(ctx, blockNumbers)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocks")
	}

	var r0 []rpc.GetBlocksResult
	if rf, ok := ret.Get(0).(func(context.Context, []*big.Int) []rpc.GetBlocksResult); ok {
		r0 = rf(ctx, blockNumbers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rpc.GetBlocksResult)
		}
	}

	return r0
}

// MockIRPCClient_GetBlocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocks'
type MockIRPCClient_GetBlocks_Call struct {
	*mock.Call
}

// GetBlocks is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNumbers []*big.Int
func (_e *MockIRPCClient_Expecter) GetBlocks(ctx interface{}, blockNumbers interface{}) *MockIRPCClient_GetBlocks_Call {
	return &MockIRPCClient_GetBlocks_Call{Call: _e.mock.On("GetBlocks", ctx, blockNumbers)}
}

func (_c *MockIRPCClient_GetBlocks_Call) Run(run func(ctx context.Context, blockNumbers []*big.Int)) *MockIRPCClient_GetBlocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*big.Int))
	})
	return _c
}

func (_c *MockIRPCClient_GetBlocks_Call) Return(_a0 []rpc.GetBlocksResult) *MockIRPCClient_GetBlocks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRPCClient_GetBlocks_Call) RunAndReturn(run func(context.Context, []*big.Int) []rpc.GetBlocksResult) *MockIRPCClient_GetBlocks_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlocksPerRequest provides a mock function with no fields
func (_m *MockIRPCClient) GetBlocksPerRequest() rpc.BlocksPerRequestConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBlocksPerRequest")
	}

	var r0 rpc.BlocksPerRequestConfig
	if rf, ok := ret.Get(0).(func() rpc.BlocksPerRequestConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(rpc.BlocksPerRequestConfig)
	}

	return r0
}

// MockIRPCClient_GetBlocksPerRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocksPerRequest'
type MockIRPCClient_GetBlocksPerRequest_Call struct {
	*mock.Call
}

// GetBlocksPerRequest is a helper method to define mock.On call
func (_e *MockIRPCClient_Expecter) GetBlocksPerRequest() *MockIRPCClient_GetBlocksPerRequest_Call {
	return &MockIRPCClient_GetBlocksPerRequest_Call{Call: _e.mock.On("GetBlocksPerRequest")}
}

func (_c *MockIRPCClient_GetBlocksPerRequest_Call) Run(run func()) *MockIRPCClient_GetBlocksPerRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRPCClient_GetBlocksPerRequest_Call) Return(_a0 rpc.BlocksPerRequestConfig) *MockIRPCClient_GetBlocksPerRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRPCClient_GetBlocksPerRequest_Call) RunAndReturn(run func() rpc.BlocksPerRequestConfig) *MockIRPCClient_GetBlocksPerRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetChainID provides a mock function with no fields
func (_m *MockIRPCClient) GetChainID() *big.Int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChainID")
	}

	var r0 *big.Int
	if rf, ok := ret.Get(0).(func() *big.Int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	return r0
}

// MockIRPCClient_GetChainID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChainID'
type MockIRPCClient_GetChainID_Call struct {
	*mock.Call
}

// GetChainID is a helper method to define mock.On call
func (_e *MockIRPCClient_Expecter) GetChainID() *MockIRPCClient_GetChainID_Call {
	return &MockIRPCClient_GetChainID_Call{Call: _e.mock.On("GetChainID")}
}

func (_c *MockIRPCClient_GetChainID_Call) Run(run func()) *MockIRPCClient_GetChainID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRPCClient_GetChainID_Call) Return(_a0 *big.Int) *MockIRPCClient_GetChainID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRPCClient_GetChainID_Call) RunAndReturn(run func() *big.Int) *MockIRPCClient_GetChainID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFullBlocks provides a mock function with given fields: ctx, blockNumbers
func (_m *MockIRPCClient) GetFullBlocks(ctx context.Context, blockNumbers []*big.Int) []rpc.GetFullBlockResult {
	ret := _m.Called(ctx, blockNumbers)

	if len(ret) == 0 {
		panic("no return value specified for GetFullBlocks")
	}

	var r0 []rpc.GetFullBlockResult
	if rf, ok := ret.Get(0).(func(context.Context, []*big.Int) []rpc.GetFullBlockResult); ok {
		r0 = rf(ctx, blockNumbers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rpc.GetFullBlockResult)
		}
	}

	return r0
}

// MockIRPCClient_GetFullBlocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFullBlocks'
type MockIRPCClient_GetFullBlocks_Call struct {
	*mock.Call
}

// GetFullBlocks is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNumbers []*big.Int
func (_e *MockIRPCClient_Expecter) GetFullBlocks(ctx interface{}, blockNumbers interface{}) *MockIRPCClient_GetFullBlocks_Call {
	return &MockIRPCClient_GetFullBlocks_Call{Call: _e.mock.On("GetFullBlocks", ctx, blockNumbers)}
}

func (_c *MockIRPCClient_GetFullBlocks_Call) Run(run func(ctx context.Context, blockNumbers []*big.Int)) *MockIRPCClient_GetFullBlocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*big.Int))
	})
	return _c
}

func (_c *MockIRPCClient_GetFullBlocks_Call) Return(_a0 []rpc.GetFullBlockResult) *MockIRPCClient_GetFullBlocks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRPCClient_GetFullBlocks_Call) RunAndReturn(run func(context.Context, []*big.Int) []rpc.GetFullBlockResult) *MockIRPCClient_GetFullBlocks_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestBlockNumber provides a mock function with given fields: ctx
func (_m *MockIRPCClient) GetLatestBlockNumber(ctx context.Context) (*big.Int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlockNumber")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*big.Int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *big.Int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRPCClient_GetLatestBlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestBlockNumber'
type MockIRPCClient_GetLatestBlockNumber_Call struct {
	*mock.Call
}

// GetLatestBlockNumber is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIRPCClient_Expecter) GetLatestBlockNumber(ctx interface{}) *MockIRPCClient_GetLatestBlockNumber_Call {
	return &MockIRPCClient_GetLatestBlockNumber_Call{Call: _e.mock.On("GetLatestBlockNumber", ctx)}
}

func (_c *MockIRPCClient_GetLatestBlockNumber_Call) Run(run func(ctx context.Context)) *MockIRPCClient_GetLatestBlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIRPCClient_GetLatestBlockNumber_Call) Return(_a0 *big.Int, _a1 error) *MockIRPCClient_GetLatestBlockNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRPCClient_GetLatestBlockNumber_Call) RunAndReturn(run func(context.Context) (*big.Int, error)) *MockIRPCClient_GetLatestBlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactions provides a mock function with given fields: ctx, txHashes
func (_m *MockIRPCClient) GetTransactions(ctx context.Context, txHashes []string) []rpc.GetTransactionsResult {
	ret := _m.Called(ctx, txHashes)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactions")
	}

	var r0 []rpc.GetTransactionsResult
	if rf, ok := ret.Get(0).(func(context.Context, []string) []rpc.GetTransactionsResult); ok {
		r0 = rf(ctx, txHashes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rpc.GetTransactionsResult)
		}
	}

	return r0
}

// MockIRPCClient_GetTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactions'
type MockIRPCClient_GetTransactions_Call struct {
	*mock.Call
}

// GetTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - txHashes []string
func (_e *MockIRPCClient_Expecter) GetTransactions(ctx interface{}, txHashes interface{}) *MockIRPCClient_GetTransactions_Call {
	return &MockIRPCClient_GetTransactions_Call{Call: _e.mock.On("GetTransactions", ctx, txHashes)}
}

func (_c *MockIRPCClient_GetTransactions_Call) Run(run func(ctx context.Context, txHashes []string)) *MockIRPCClient_GetTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockIRPCClient_GetTransactions_Call) Return(_a0 []rpc.GetTransactionsResult) *MockIRPCClient_GetTransactions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRPCClient_GetTransactions_Call) RunAndReturn(run func(context.Context, []string) []rpc.GetTransactionsResult) *MockIRPCClient_GetTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function with no fields
func (_m *MockIRPCClient) GetURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIRPCClient_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockIRPCClient_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
func (_e *MockIRPCClient_Expecter) GetURL() *MockIRPCClient_GetURL_Call {
	return &MockIRPCClient_GetURL_Call{Call: _e.mock.On("GetURL")}
}

func (_c *MockIRPCClient_GetURL_Call) Run(run func()) *MockIRPCClient_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRPCClient_GetURL_Call) Return(_a0 string) *MockIRPCClient_GetURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRPCClient_GetURL_Call) RunAndReturn(run func() string) *MockIRPCClient_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// HasCode provides a mock function with given fields: ctx, address
func (_m *MockIRPCClient) HasCode(ctx context.Context, address string) (bool, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for HasCode")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, address)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRPCClient_HasCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasCode'
type MockIRPCClient_HasCode_Call struct {
	*mock.Call
}

// HasCode is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *MockIRPCClient_Expecter) HasCode(ctx interface{}, address interface{}) *MockIRPCClient_HasCode_Call {
	return &MockIRPCClient_HasCode_Call{Call: _e.mock.On("HasCode", ctx, address)}
}

func (_c *MockIRPCClient_HasCode_Call) Run(run func(ctx context.Context, address string)) *MockIRPCClient_HasCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIRPCClient_HasCode_Call) Return(_a0 bool, _a1 error) *MockIRPCClient_HasCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRPCClient_HasCode_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockIRPCClient_HasCode_Call {
	_c.Call.Return(run)
	return _c
}

// IsWebsocket provides a mock function with no fields
func (_m *MockIRPCClient) IsWebsocket() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsWebsocket")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockIRPCClient_IsWebsocket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsWebsocket'
type MockIRPCClient_IsWebsocket_Call struct {
	*mock.Call
}

// IsWebsocket is a helper method to define mock.On call
func (_e *MockIRPCClient_Expecter) IsWebsocket() *MockIRPCClient_IsWebsocket_Call {
	return &MockIRPCClient_IsWebsocket_Call{Call: _e.mock.On("IsWebsocket")}
}

func (_c *MockIRPCClient_IsWebsocket_Call) Run(run func()) *MockIRPCClient_IsWebsocket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRPCClient_IsWebsocket_Call) Return(_a0 bool) *MockIRPCClient_IsWebsocket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRPCClient_IsWebsocket_Call) RunAndReturn(run func() bool) *MockIRPCClient_IsWebsocket_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsBlockReceipts provides a mock function with no fields
func (_m *MockIRPCClient) SupportsBlockReceipts() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsBlockReceipts")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockIRPCClient_SupportsBlockReceipts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsBlockReceipts'
type MockIRPCClient_SupportsBlockReceipts_Call struct {
	*mock.Call
}

// SupportsBlockReceipts is a helper method to define mock.On call
func (_e *MockIRPCClient_Expecter) SupportsBlockReceipts() *MockIRPCClient_SupportsBlockReceipts_Call {
	return &MockIRPCClient_SupportsBlockReceipts_Call{Call: _e.mock.On("SupportsBlockReceipts")}
}

func (_c *MockIRPCClient_SupportsBlockReceipts_Call) Run(run func()) *MockIRPCClient_SupportsBlockReceipts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRPCClient_SupportsBlockReceipts_Call) Return(_a0 bool) *MockIRPCClient_SupportsBlockReceipts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRPCClient_SupportsBlockReceipts_Call) RunAndReturn(run func() bool) *MockIRPCClient_SupportsBlockReceipts_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsTraceBlock provides a mock function with no fields
func (_m *MockIRPCClient) SupportsTraceBlock() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsTraceBlock")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockIRPCClient_SupportsTraceBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsTraceBlock'
type MockIRPCClient_SupportsTraceBlock_Call struct {
	*mock.Call
}

// SupportsTraceBlock is a helper method to define mock.On call
func (_e *MockIRPCClient_Expecter) SupportsTraceBlock() *MockIRPCClient_SupportsTraceBlock_Call {
	return &MockIRPCClient_SupportsTraceBlock_Call{Call: _e.mock.On("SupportsTraceBlock")}
}

func (_c *MockIRPCClient_SupportsTraceBlock_Call) Run(run func()) *MockIRPCClient_SupportsTraceBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRPCClient_SupportsTraceBlock_Call) Return(_a0 bool) *MockIRPCClient_SupportsTraceBlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRPCClient_SupportsTraceBlock_Call) RunAndReturn(run func() bool) *MockIRPCClient_SupportsTraceBlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRPCClient creates a new instance of MockIRPCClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRPCClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRPCClient {
	mock := &MockIRPCClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
