// Code generated by mockery v2.53.5. DO NOT EDIT.

//go:build !production

package mocks

import (
	big "math/big"

	mock "github.com/stretchr/testify/mock"
	common "github.com/thirdweb-dev/indexer/internal/common"

	storage "github.com/thirdweb-dev/indexer/internal/storage"
)

// MockIStagingStorage is an autogenerated mock type for the IStagingStorage type
type MockIStagingStorage struct {
	mock.Mock
}

type MockIStagingStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStagingStorage) EXPECT() *MockIStagingStorage_Expecter {
	return &MockIStagingStorage_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockIStagingStorage) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIStagingStorage_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIStagingStorage_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIStagingStorage_Expecter) Close() *MockIStagingStorage_Close_Call {
	return &MockIStagingStorage_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIStagingStorage_Close_Call) Run(run func()) *MockIStagingStorage_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIStagingStorage_Close_Call) Return(_a0 error) *MockIStagingStorage_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIStagingStorage_Close_Call) RunAndReturn(run func() error) *MockIStagingStorage_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStagingDataOlderThan provides a mock function with given fields: chainId, blockNumber
func (_m *MockIStagingStorage) DeleteStagingDataOlderThan(chainId *big.Int, blockNumber *big.Int) error {
	ret := _m.Called(chainId, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStagingDataOlderThan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*big.Int, *big.Int) error); ok {
		r0 = rf(chainId, blockNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIStagingStorage_DeleteStagingDataOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStagingDataOlderThan'
type MockIStagingStorage_DeleteStagingDataOlderThan_Call struct {
	*mock.Call
}

// DeleteStagingDataOlderThan is a helper method to define mock.On call
//   - chainId *big.Int
//   - blockNumber *big.Int
func (_e *MockIStagingStorage_Expecter) DeleteStagingDataOlderThan(chainId interface{}, blockNumber interface{}) *MockIStagingStorage_DeleteStagingDataOlderThan_Call {
	return &MockIStagingStorage_DeleteStagingDataOlderThan_Call{Call: _e.mock.On("DeleteStagingDataOlderThan", chainId, blockNumber)}
}

func (_c *MockIStagingStorage_DeleteStagingDataOlderThan_Call) Run(run func(chainId *big.Int, blockNumber *big.Int)) *MockIStagingStorage_DeleteStagingDataOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*big.Int), args[1].(*big.Int))
	})
	return _c
}

func (_c *MockIStagingStorage_DeleteStagingDataOlderThan_Call) Return(_a0 error) *MockIStagingStorage_DeleteStagingDataOlderThan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIStagingStorage_DeleteStagingDataOlderThan_Call) RunAndReturn(run func(*big.Int, *big.Int) error) *MockIStagingStorage_DeleteStagingDataOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// GetStagingData provides a mock function with given fields: qf
func (_m *MockIStagingStorage) GetStagingData(qf storage.QueryFilter) ([]common.BlockData, error) {
	ret := _m.Called(qf)

	if len(ret) == 0 {
		panic("no return value specified for GetStagingData")
	}

	var r0 []common.BlockData
	var r1 error
	if rf, ok := ret.Get(0).(func(storage.QueryFilter) ([]common.BlockData, error)); ok {
		return rf(qf)
	}
	if rf, ok := ret.Get(0).(func(storage.QueryFilter) []common.BlockData); ok {
		r0 = rf(qf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.BlockData)
		}
	}

	if rf, ok := ret.Get(1).(func(storage.QueryFilter) error); ok {
		r1 = rf(qf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIStagingStorage_GetStagingData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStagingData'
type MockIStagingStorage_GetStagingData_Call struct {
	*mock.Call
}

// GetStagingData is a helper method to define mock.On call
//   - qf storage.QueryFilter
func (_e *MockIStagingStorage_Expecter) GetStagingData(qf interface{}) *MockIStagingStorage_GetStagingData_Call {
	return &MockIStagingStorage_GetStagingData_Call{Call: _e.mock.On("GetStagingData", qf)}
}

func (_c *MockIStagingStorage_GetStagingData_Call) Run(run func(qf storage.QueryFilter)) *MockIStagingStorage_GetStagingData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(storage.QueryFilter))
	})
	return _c
}

func (_c *MockIStagingStorage_GetStagingData_Call) Return(data []common.BlockData, err error) *MockIStagingStorage_GetStagingData_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *MockIStagingStorage_GetStagingData_Call) RunAndReturn(run func(storage.QueryFilter) ([]common.BlockData, error)) *MockIStagingStorage_GetStagingData_Call {
	_c.Call.Return(run)
	return _c
}

// GetStagingDataBlockRange provides a mock function with given fields: chainId
func (_m *MockIStagingStorage) GetStagingDataBlockRange(chainId *big.Int) (*big.Int, *big.Int, error) {
	ret := _m.Called(chainId)

	if len(ret) == 0 {
		panic("no return value specified for GetStagingDataBlockRange")
	}

	var r0 *big.Int
	var r1 *big.Int
	var r2 error
	if rf, ok := ret.Get(0).(func(*big.Int) (*big.Int, *big.Int, error)); ok {
		return rf(chainId)
	}
	if rf, ok := ret.Get(0).(func(*big.Int) *big.Int); ok {
		r0 = rf(chainId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*big.Int) *big.Int); ok {
		r1 = rf(chainId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*big.Int)
		}
	}

	if rf, ok := ret.Get(2).(func(*big.Int) error); ok {
		r2 = rf(chainId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIStagingStorage_GetStagingDataBlockRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStagingDataBlockRange'
type MockIStagingStorage_GetStagingDataBlockRange_Call struct {
	*mock.Call
}

// GetStagingDataBlockRange is a helper method to define mock.On call
//   - chainId *big.Int
func (_e *MockIStagingStorage_Expecter) GetStagingDataBlockRange(chainId interface{}) *MockIStagingStorage_GetStagingDataBlockRange_Call {
	return &MockIStagingStorage_GetStagingDataBlockRange_Call{Call: _e.mock.On("GetStagingDataBlockRange", chainId)}
}

func (_c *MockIStagingStorage_GetStagingDataBlockRange_Call) Run(run func(chainId *big.Int)) *MockIStagingStorage_GetStagingDataBlockRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*big.Int))
	})
	return _c
}

func (_c *MockIStagingStorage_GetStagingDataBlockRange_Call) Return(minBlockNumber *big.Int, maxBlockNumber *big.Int, err error) *MockIStagingStorage_GetStagingDataBlockRange_Call {
	_c.Call.Return(minBlockNumber, maxBlockNumber, err)
	return _c
}

func (_c *MockIStagingStorage_GetStagingDataBlockRange_Call) RunAndReturn(run func(*big.Int) (*big.Int, *big.Int, error)) *MockIStagingStorage_GetStagingDataBlockRange_Call {
	_c.Call.Return(run)
	return _c
}

// InsertStagingData provides a mock function with given fields: data
func (_m *MockIStagingStorage) InsertStagingData(data []common.BlockData) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for InsertStagingData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]common.BlockData) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIStagingStorage_InsertStagingData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertStagingData'
type MockIStagingStorage_InsertStagingData_Call struct {
	*mock.Call
}

// InsertStagingData is a helper method to define mock.On call
//   - data []common.BlockData
func (_e *MockIStagingStorage_Expecter) InsertStagingData(data interface{}) *MockIStagingStorage_InsertStagingData_Call {
	return &MockIStagingStorage_InsertStagingData_Call{Call: _e.mock.On("InsertStagingData", data)}
}

func (_c *MockIStagingStorage_InsertStagingData_Call) Run(run func(data []common.BlockData)) *MockIStagingStorage_InsertStagingData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]common.BlockData))
	})
	return _c
}

func (_c *MockIStagingStorage_InsertStagingData_Call) Return(_a0 error) *MockIStagingStorage_InsertStagingData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIStagingStorage_InsertStagingData_Call) RunAndReturn(run func([]common.BlockData) error) *MockIStagingStorage_InsertStagingData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIStagingStorage creates a new instance of MockIStagingStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStagingStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStagingStorage {
	mock := &MockIStagingStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
